# Generated by Django 4.2.23 on 2025-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending Review'), ('Reviewed', 'Reviewed'), ('Action Required', 'Action Required')], default='Pending Review', max_length=20),
        ),
    ]
